### PR TITLE
Reduce batch size from 20 to 10

### PR DESCRIPTION
**Pull request by jjoonathan**
Actual commit is gross but it's a straightforward change. Quick reminder.

### CODE REVIEW

**Comment by jjoonathan** [comment]
Before: resource limit exceeded please contact your AWS rep blah blah...

After: 
```
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-05-51-434726
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-05-53-246971
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-05-56-231498
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-05-58-789342
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-06-00-629661
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-06-02-372601
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-06-04-612111
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-06-06-210605
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-06-07-998845
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-06-09-553540

Waiting for batch 0:
......................

INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-09-53-352140
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-09-54-989336
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-00-691814
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-02-825892
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-04-453925
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-06-185184
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-07-862326
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-09-625716
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-11-333647
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-10-13-401861

Waiting for batch 1:
.......................

INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-07-572328
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-09-235080
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-11-661325
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-14-273692
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-15-880069
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-17-550344
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-19-092000
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-21-792440
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-23-833676
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-14-27-454628

Waiting for batch 2:
.......................

INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-20-895866
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-22-714583
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-26-587094
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-28-302402
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-30-259032
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-32-121253
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-33-922746
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-35-689063
INFO:sagemaker:Creating training-job with name: kmeans-2018-11-27-23-18-38-224064

Waiting for batch 3:
.....................
Done
```

**Comment by wleepang** [comment]
I see what you did and I think it would be good to use the `chunk()` function a couple cells below to split the model training based on a batch size.

Odd thing is that I can see your diff in this PR, but when I pull it down from your master branch I don't see any changes.

**Comment by wleepang** [comment]
I addressed the points of the original PR by moving the `chunk` function as described.

**Comment by jjoonathan** [comment]
Sounds good!

Cheers,
Jon

**Pull request closed without merging**
